version: '3'

services:
  demo2_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - demo-network
    container_name: "demo2-container"

networks:
  demo-network:
    external: true